CREATE TABLE LECTORES(
	ID SERIAL PRIMARY KEY,
	NOMBRE VARCHAR (100) NOT NULL,
	APELLIDO VARCHAR (100) NOT NULL,
	EMAIL VARCHAR (100) NOT NULL,
	FECHA_NACIMIENTO  DATE NOT NULL
);

SELECT * FROM LECTORES;

INSERT INTO LECTORE VALUES  ( DEFAULT, 'JUAN ALBERTO', 'CORTEZ', 'JUANCORTEZ@GMAIL.COM', '20/06/1983');
INSERT INTO LECTORES VALUES ( DEFAULT, 'ANTONIA', 'DE LOS RIOS', 'ANTONIARIOS@YAHOO.COM', '24/11/1978');
INSERT INTO LECTORES VALUES ( DEFAULT, 'NICOLAS', 'MARTIN', 'NICO_MARTIN23@GMAIL.COM', '11/07/1986');
INSERT INTO LECTORES VALUES ( DEFAULT, 'NESTOR', 'CASCO', 'NESTOR_CASCO2331@HOTMAIL.COM', '11/02/1981');
INSERT INTO LECTORES VALUES ( DEFAULT, 'LISA', 'PEREZ', 'LISPEREZ@HOTMAIL.COM', '11/08/1994');
INSERT INTO LECTORES VALUES ( DEFAULT, 'ANA ROSA', 'ESTAGNOLLI', 'ANROS@ABCDATOS.COM', '15/10/1974');
INSERT INTO LECTORES VALUES ( DEFAULT, 'MILAGROS', 'PASTORUTI', 'MILI_2231@GMAIL.COM', '22/01/2001');
INSERT INTO LECTORES VALUES ( DEFAULT, 'PEDRO', 'ALONZO', 'ALONZO.PEDRO@IMPERMEBILIZANTESROSARIO.COM', '05/09/1983');
INSERT INTO LECTORES VALUES ( DEFAULT, 'ARTURO EZEQUIEL', 'RAMIREZ', 'ARTU.RAMA@OUTLOOK.COM', '29/03/1998');
INSERT INTO LECTORES VALUES ( DEFAULT, 'JUAN IGNACIO', 'ALTAREZ', 'JUANALTAREZ.223@YAHOO.COM', '24/08/1975');						 


CREATE TABLE LIBROS(
ID SERIAL PRIMARY KEY,
NOMBRE VARCHAR (100) NOT NULL,
EDITORIAL VARCHAR (100),
AUTOR VARCHAR (100),
ISBN INT
);

SELECT * FROM LIBROS;

INSERT INTO LIBROS VALUES (DEFAULT, 'CEMENTERIOS DE ANIMALES', 'EDICION DE MENTE', 'STEPHEN KING', '4568874');
INSERT INTO LIBROS VALUES (DEFAULT, 'EN EL NOMBRE DE LAS ROSAS', 'EDITIORIAL ESPAÑA', 'UMBERTO ECO', '44558877');
INSERT INTO LIBROS VALUES (DEFAULT, 'CIEN AÑOS DE SOLEDAD', 'SUDAMERICANA', 'GABRIEL GARCIA MARQUEZ', '7788845');
INSERT INTO LIBROS VALUES (DEFAULT, 'EL DIARIO DE ELLEN RIMBAUER', 'EDITORIAL MAINE', 'STEPHEN KING', '44699874');
INSERT INTO LIBROS VALUES (DEFAULT, 'LA OJARASCA', 'SUDAMERICANA', 'GABRIEL GARCIA MARQUEZ', '25641111');
INSERT INTO LIBROS VALUES (DEFAULT, 'EL AMOR EN TIEMPOS DE COLERA', 'SUDAMERICANA', 'GABRIEL GARCIA MARQUEZ', '25641111');
INSERT INTO LIBROS VALUES (DEFAULT, 'LA CASA DE LOS ESPIRITUS', 'EDICION CHILE', 'ISABEL ALLENDE', '22545447');
INSERT INTO LIBROS VALUES (DEFAULT, 'PAULA', 'EDICION CHILE', 'ISABEL ALLENDE', '25545447');
INSERT INTO LIBROS VALUES (DEFAULT, 'LA TREGUA', 'ALFA', 'MARIO BENEDETTI', '2225412');
INSERT INTO LIBROS VALUES (DEFAULT, 'GRACIAS POR EL FUEGO', 'ALFA', 'MARIO BENEDETTI', '88541254');

CREATE TABLE REGISTRO(
ID_LECTORES INT,
ID_LIBROS INT,
FECHA_SALIDA DATE, 
FECHA_ENTRADA DATE,
CONSTRAINT PK_ID_LECTORES_ID_LIBROS PRIMARY KEY (ID_LECTORES, ID_LIBROS),
CONSTRAINT FK_REGISTRO_ID_LECTORES FOREIGN KEY(ID_LECTORES) REFERENCES LECTORES(ID),
CONSTRAINT FK_REGISTRO_ID_LIBROS FOREIGN KEY (ID_LIBROS) REFERENCES LIBROS(ID)
);

SELECT * FROM REGISTRO;

INSERT INTO REGISTRO VALUES (1, 1, 'CURRENT_DATE', 'CURRENT_DATE');
INSERT INTO REGISTRO VALUES (1, 2, 'CURRENT_DATE', 'CURRENT_DATE');
INSERT INTO REGISTRO VALUES (1, 3, 'CURRENT_DATE', 'CURRENT_DATE');
INSERT INTO REGISTRO VALUES (1, 4, '2022-02-04', 'CURRENT_DATE');
INSERT INTO REGISTRO VALUES (1, 5, '2022-01-04', '2022-07-08');

INSERT INTO REGISTRO VALUES (2, 6, 'CURRENT_DATE', 'CURRENT_DATE');
INSERT INTO REGISTRO VALUES (2, 7, 'CURRENT_DATE', 'CURRENT_DATE');
INSERT INTO REGISTRO VALUES (2, 8, , 'CURRENT_DATE');
INSERT INTO REGISTRO VALUES (2, 9, '2022-02-04', 'CURRENT_DATE');
INSERT INTO REGISTRO VALUES (2, 10, '2022-01-04', '2022-07-08');

INSERT INTO REGISTRO VALUES (4, 1, 'CURRENT_DATE', 'CURRENT_DATE');
INSERT INTO REGISTRO VALUES (4, 3, 'CURRENT_DATE', 'CURRENT_DATE');
INSERT INTO REGISTRO VALUES (4, 5, 'CURRENT_DATE', 'CURRENT_DATE');
INSERT INTO REGISTRO VALUES (4, 7, '2022-02-04', 'CURRENT_DATE');
INSERT INTO REGISTRO VALUES (4, 9, '2022-01-04', '2022-07-08');

INSERT INTO REGISTRO VALUES (9, 2, 'CURRENT_DATE', 'CURRENT_DATE');
INSERT INTO REGISTRO VALUES (9, 4, 'CURRENT_DATE', 'CURRENT_DATE');
INSERT INTO REGISTRO VALUES (9, 6, 'CURRENT_DATE', 'CURRENT_DATE');
INSERT INTO REGISTRO VALUES (9, 8, '2022-02-04', 'CURRENT_DATE');
INSERT INTO REGISTRO VALUES (9, 10, '2022-01-04', '2022-07-08');


INSERT INTO REGISTRO VALUES (5, 6, '2023-06-03', '2023-08-12');
INSERT INTO REGISTRO VALUES (5, 8, '2022-02-04', '2023-02-04');
INSERT INTO REGISTRO VALUES (5, 10, '2022-07-04', '2023-07-04');

INSERT INTO REGISTRO VALUES (6, 3, '2023-06-03', '2023-08-12');
INSERT INTO REGISTRO VALUES (6, 2, '2022-02-04', '2023-02-04');
INSERT INTO REGISTRO VALUES (6, 1, '2022-07-04', '2023-07-04');

INSERT INTO REGISTRO VALUES (7, 7, '2023-06-03', '2023-08-12');
INSERT INTO REGISTRO VALUES (7, 8, '2022-02-04', '2023-02-04');
INSERT INTO REGISTRO VALUES (7, 9, '2022-07-04', '2023-07-04');

INSERT INTO REGISTRO VALUES (8, 9, '2023-10-04', '2023-12-12');

INSERT INTO REGISTRO VALUES (10, 7, '2023-02-12');


SELECT ID_LIBROS, COUNT (ID_LIBROS) AS CANTIDAD_PRESTAMOS
FROM REGISTRO 
GROUP BY ID_LIBROS
ORDER BY CANTIDAD_PRESTAMOS D
SELECT COUNT (ID_LECTORES) FROM REGISTRO WHERE ID_LECTORES = 6;
SELECT COUNT (ID_LECTORES) FROM REGISTRO;

DELETE FROM REGISTRO WHERE ID_LECTORES = 1 AND ID_LIBROS = 2;

SELECT * FROM REGISTRO;

###################################################################################################################################

SELECT AVG (DATE_PART ('YEAR', AGE (FECHA_NACIMIENTO))) AS PROMEDIO_EDAD FROM LECTORES;

SELECT MAX (DATE_PART('YEAR', AGE(FECHA_NACIMIENTO))) AS MAYOR_EDAD FROM LECTORES;

SELECT MIN (DATE_PART('YEAR', AGE(FECHA_NACIMIENTO))) AS MENOR_EDAD FROM LECTORES;

SELECT 
AVG(DATE_PART ('YEAR', AGE (FECHA_NACIMIENTO))) AS PROMEDIO_EDAD,
MAX(DATE_PART ('YEAR', AGE (FECHA_NACIMIENTO))) AS MAYOR_EDAD,
MIN(DATE_PART ('YEAR', AGE (FECHA_NACIMIENTO))) AS MENOR_EDAD
FROM LECTORES;

####################################################################################################################################

CREATE OR REPLACE VIEW LIBROS_PRESTADOS AS SELECT
LECTORES.NOMBRE, LECTORES.APELLIDO, LIBROS.NOMBRE AS NOMBRELIBRO, LIBROS.EDITORIAL, LIBROS.ISBN
FROM LECTORES
INNER JOIN REGISTRO ON REGISTRO.ID_LECTORES = LECTORES.ID
INNER JOIN LIBROS ON REGISTRO.ID_LIBROS = LIBROS.ID;

SELECT * FROM LIBROS_PRESTADOS;

SELECT * FROM LIBROS_PRESTADOS WHERE NOMBRE = 'JUAN ALBERTO' AND APELLIDO = 'CORTEZ';

#######################################################################################################################################
--4.1 
CREATE OR REPLACE FUNCTION DEVOLVER_LIBRO(ID_LECTORES INT, ID_LIBROS INT)
RETURNS VOID AS $$ 
BEGIN
	DELETE FROM REGISTRO
	WHERE REGISTRO.ID_LECTORES = ID_LECTORES AND REGISTRO.ID_LIBROS = ID_LIBROS;
END;

$$ LANGUAGE PLPGSQL

--LLAMANDO A LA FUNCION 
SELECT * FROM DEVOLVER_LIBRO (1, 3);

--4.2 tabla de logs almacena el identificador de lector y el identificador de libro junto a la fecha hora de la devolucion.

CREATE TABLE DEVOLUCION_LOG(
	ID_LECTORES INTEGER NOT NULL,
	ID_LIBROS INTEGER NOT NULL,
	FECHA TIMESTAMP
);

-- funcion trigger

CREATE OR REPLACE FUNCTION FUNCION_TR_DELETE() RETURNS TRIGGER
AS $$
BEGIN

	INSERT INTO DEVOLUCION_LOG(ID_LECTORES, ID_LIBROS, FECHA) VALUES 
	(OLD.ID_LECTORES, OLD.ID_LIBROS, NOW());
	
	RETURN OLD;
END
$$
LANGUAGE PLPGSQL;

CREATE TRIGGER TRIGGER_DELET BEFORE DELETE ON REGISTRO
FOR EACH ROW
EXECUTE PROCEDURE FUNCION_TR_DELETE();

--RETURN OLD;

SELECT * FROM DEVOLVERLIBRO (1, 4);

SELECT * FROM DEVOLUCION_LOG (1, 4);

SELECT * FROM REGISTRO;

--4.3 FUNCION LIBROS_PRESTADOS PARA SABER LA CANTIDAD DE LIBROS PRESTADOS ACTUALMENTE.

CREATE OR REPLACE FUNCTION LIBROS_PRESTADOS (INTEGER) RETURNS BIGINT AS;
'SELECT COUNT(ID_LIBROS) AS CANTIDAD FROM REGISTRO WHERE ID_LIBROS = $1;'

LANGUAGE SQL;

SELECT LIBROS_PRESTADOS (1);
